<?php

return [
    // Europe
    ['name' => 'France', 'short_name' => 'FRA', 'flag' => 'https://flagcdn.com/w320/fr.png', 'confederation' => 'UEFA'],
    ['name' => 'Allemagne', 'short_name' => 'GER', 'flag' => 'https://flagcdn.com/w320/de.png', 'confederation' => 'UEFA'],
    ['name' => 'Espagne', 'short_name' => 'ESP', 'flag' => 'https://flagcdn.com/w320/es.png', 'confederation' => 'UEFA'],
    ['name' => 'Italie', 'short_name' => 'ITA', 'flag' => 'https://flagcdn.com/w320/it.png', 'confederation' => 'UEFA'],
    ['name' => 'Angleterre', 'short_name' => 'ENG', 'flag' => 'https://flagcdn.com/w320/gb-eng.png', 'confederation' => 'UEFA'],
    ['name' => 'Portugal', 'short_name' => 'POR', 'flag' => 'https://flagcdn.com/w320/pt.png', 'confederation' => 'UEFA'],
    ['name' => 'Pays-Bas', 'short_name' => 'NED', 'flag' => 'https://flagcdn.com/w320/nl.png', 'confederation' => 'UEFA'],
    ['name' => 'Belgique', 'short_name' => 'BEL', 'flag' => 'https://flagcdn.com/w320/be.png', 'confederation' => 'UEFA'],
    ['name' => 'Croatie', 'short_name' => 'CRO', 'flag' => 'https://flagcdn.com/w320/hr.png', 'confederation' => 'UEFA'],
    ['name' => 'Suisse', 'short_name' => 'SUI', 'flag' => 'https://flagcdn.com/w320/ch.png', 'confederation' => 'UEFA'],
    ['name' => 'Danemark', 'short_name' => 'DEN', 'flag' => 'https://flagcdn.com/w320/dk.png', 'confederation' => 'UEFA'],
    ['name' => 'Suède', 'short_name' => 'SWE', 'flag' => 'https://flagcdn.com/w320/se.png', 'confederation' => 'UEFA'],
    ['name' => 'Pologne', 'short_name' => 'POL', 'flag' => 'https://flagcdn.com/w320/pl.png', 'confederation' => 'UEFA'],
    ['name' => 'Autriche', 'short_name' => 'AUT', 'flag' => 'https://flagcdn.com/w320/at.png', 'confederation' => 'UEFA'],
    ['name' => 'Ukraine', 'short_name' => 'UKR', 'flag' => 'https://flagcdn.com/w320/ua.png', 'confederation' => 'UEFA'],
    ['name' => 'Serbie', 'short_name' => 'SRB', 'flag' => 'https://flagcdn.com/w320/rs.png', 'confederation' => 'UEFA'],
    ['name' => 'Tchéquie', 'short_name' => 'CZE', 'flag' => 'https://flagcdn.com/w320/cz.png', 'confederation' => 'UEFA'],
    ['name' => 'Roumanie', 'short_name' => 'ROU', 'flag' => 'https://flagcdn.com/w320/ro.png', 'confederation' => 'UEFA'],
    ['name' => 'Slovaquie', 'short_name' => 'SVK', 'flag' => 'https://flagcdn.com/w320/sk.png', 'confederation' => 'UEFA'],
    ['name' => 'Hongrie', 'short_name' => 'HUN', 'flag' => 'https://flagcdn.com/w320/hu.png', 'confederation' => 'UEFA'],
    ['name' => 'Grèce', 'short_name' => 'GRE', 'flag' => 'https://flagcdn.com/w320/gr.png', 'confederation' => 'UEFA'],
    ['name' => 'Turquie', 'short_name' => 'TUR', 'flag' => 'https://flagcdn.com/w320/tr.png', 'confederation' => 'UEFA'],
    ['name' => 'Norvège', 'short_name' => 'NOR', 'flag' => 'https://flagcdn.com/w320/no.png', 'confederation' => 'UEFA'],
    ['name' => 'Irlande', 'short_name' => 'IRL', 'flag' => 'https://flagcdn.com/w320/ie.png', 'confederation' => 'UEFA'],
    ['name' => 'Slovénie', 'short_name' => 'SVN', 'flag' => 'https://flagcdn.com/w320/si.png', 'confederation' => 'UEFA'],
    ['name' => 'Albanie', 'short_name' => 'ALB', 'flag' => 'https://flagcdn.com/w320/al.png', 'confederation' => 'UEFA'],
    ['name' => 'Macédoine du Nord', 'short_name' => 'MKD', 'flag' => 'https://flagcdn.com/w320/mk.png', 'confederation' => 'UEFA'],
    ['name' => 'Finlande', 'short_name' => 'FIN', 'flag' => 'https://flagcdn.com/w320/fi.png', 'confederation' => 'UEFA'],
    ['name' => 'Islande', 'short_name' => 'ISL', 'flag' => 'https://flagcdn.com/w320/is.png', 'confederation' => 'UEFA'],
    ['name' => 'Bosnie-Herzégovine', 'short_name' => 'BIH', 'flag' => 'https://flagcdn.com/w320/ba.png', 'confederation' => 'UEFA'],
    ['name' => 'Monténégro', 'short_name' => 'MNE', 'flag' => 'https://flagcdn.com/w320/me.png', 'confederation' => 'UEFA'],
    ['name' => 'Pays de Galles', 'short_name' => 'WAL', 'flag' => 'https://flagcdn.com/w320/gb-wls.png', 'confederation' => 'UEFA'],
    ['name' => 'Écosse', 'short_name' => 'SCO', 'flag' => 'https://flagcdn.com/w320/gb-sct.png', 'confederation' => 'UEFA'],
    ['name' => 'Irlande du Nord', 'short_name' => 'NIR', 'flag' => 'https://flagcdn.com/w320/gb-nir.png', 'confederation' => 'UEFA'],
    ['name' => 'Russie', 'short_name' => 'RUS', 'flag' => 'https://flagcdn.com/w320/ru.png', 'confederation' => 'UEFA'],
    ['name' => 'Géorgie', 'short_name' => 'GEO', 'flag' => 'https://flagcdn.com/w320/ge.png', 'confederation' => 'UEFA'],
    ['name' => 'Bulgarie', 'short_name' => 'BUL', 'flag' => 'https://flagcdn.com/w320/bg.png', 'confederation' => 'UEFA'],
    ['name' => 'Kosovo', 'short_name' => 'KOS', 'flag' => 'https://flagcdn.com/w320/xk.png', 'confederation' => 'UEFA'],
    ['name' => 'Luxembourg', 'short_name' => 'LUX', 'flag' => 'https://flagcdn.com/w320/lu.png', 'confederation' => 'UEFA'],
    ['name' => 'Arménie', 'short_name' => 'ARM', 'flag' => 'https://flagcdn.com/w320/am.png', 'confederation' => 'UEFA'],
    ['name' => 'Azerbaïdjan', 'short_name' => 'AZE', 'flag' => 'https://flagcdn.com/w320/az.png', 'confederation' => 'UEFA'],
    ['name' => 'Chypre', 'short_name' => 'CYP', 'flag' => 'https://flagcdn.com/w320/cy.png', 'confederation' => 'UEFA'],
    ['name' => 'Estonie', 'short_name' => 'EST', 'flag' => 'https://flagcdn.com/w320/ee.png', 'confederation' => 'UEFA'],
    ['name' => 'Lettonie', 'short_name' => 'LVA', 'flag' => 'https://flagcdn.com/w320/lv.png', 'confederation' => 'UEFA'],
    ['name' => 'Lituanie', 'short_name' => 'LTU', 'flag' => 'https://flagcdn.com/w320/lt.png', 'confederation' => 'UEFA'],
    ['name' => 'Moldavie', 'short_name' => 'MDA', 'flag' => 'https://flagcdn.com/w320/md.png', 'confederation' => 'UEFA'],
    ['name' => 'Biélorussie', 'short_name' => 'BLR', 'flag' => 'https://flagcdn.com/w320/by.png', 'confederation' => 'UEFA'],
    ['name' => 'Kazakhstan', 'short_name' => 'KAZ', 'flag' => 'https://flagcdn.com/w320/kz.png', 'confederation' => 'UEFA'],
    ['name' => 'Israël', 'short_name' => 'ISR', 'flag' => 'https://flagcdn.com/w320/il.png', 'confederation' => 'UEFA'],

    // Amérique du Sud
    ['name' => 'Brésil', 'short_name' => 'BRA', 'flag' => 'https://flagcdn.com/w320/br.png', 'confederation' => 'CONMEBOL'],
    ['name' => 'Argentine', 'short_name' => 'ARG', 'flag' => 'https://flagcdn.com/w320/ar.png', 'confederation' => 'CONMEBOL'],
    ['name' => 'Uruguay', 'short_name' => 'URU', 'flag' => 'https://flagcdn.com/w320/uy.png', 'confederation' => 'CONMEBOL'],
    ['name' => 'Colombie', 'short_name' => 'COL', 'flag' => 'https://flagcdn.com/w320/co.png', 'confederation' => 'CONMEBOL'],
    ['name' => 'Chili', 'short_name' => 'CHI', 'flag' => 'https://flagcdn.com/w320/cl.png', 'confederation' => 'CONMEBOL'],
    ['name' => 'Équateur', 'short_name' => 'ECU', 'flag' => 'https://flagcdn.com/w320/ec.png', 'confederation' => 'CONMEBOL'],
    ['name' => 'Pérou', 'short_name' => 'PER', 'flag' => 'https://flagcdn.com/w320/pe.png', 'confederation' => 'CONMEBOL'],
    ['name' => 'Paraguay', 'short_name' => 'PAR', 'flag' => 'https://flagcdn.com/w320/py.png', 'confederation' => 'CONMEBOL'],
    ['name' => 'Venezuela', 'short_name' => 'VEN', 'flag' => 'https://flagcdn.com/w320/ve.png', 'confederation' => 'CONMEBOL'],
    ['name' => 'Bolivie', 'short_name' => 'BOL', 'flag' => 'https://flagcdn.com/w320/bo.png', 'confederation' => 'CONMEBOL'],

    // Amérique du Nord, Centrale et Caraïbes
    ['name' => 'Mexique', 'short_name' => 'MEX', 'flag' => 'https://flagcdn.com/w320/mx.png', 'confederation' => 'CONCACAF'],
    ['name' => 'États-Unis', 'short_name' => 'USA', 'flag' => 'https://flagcdn.com/w320/us.png', 'confederation' => 'CONCACAF'],
    ['name' => 'Canada', 'short_name' => 'CAN', 'flag' => 'https://flagcdn.com/w320/ca.png', 'confederation' => 'CONCACAF'],
    ['name' => 'Costa Rica', 'short_name' => 'CRC', 'flag' => 'https://flagcdn.com/w320/cr.png', 'confederation' => 'CONCACAF'],
    ['name' => 'Panama', 'short_name' => 'PAN', 'flag' => 'https://flagcdn.com/w320/pa.png', 'confederation' => 'CONCACAF'],
    ['name' => 'Jamaïque', 'short_name' => 'JAM', 'flag' => 'https://flagcdn.com/w320/jm.png', 'confederation' => 'CONCACAF'],
    ['name' => 'Honduras', 'short_name' => 'HON', 'flag' => 'https://flagcdn.com/w320/hn.png', 'confederation' => 'CONCACAF'],
    ['name' => 'Salvador', 'short_name' => 'SLV', 'flag' => 'https://flagcdn.com/w320/sv.png', 'confederation' => 'CONCACAF'],
    ['name' => 'Guatemala', 'short_name' => 'GUA', 'flag' => 'https://flagcdn.com/w320/gt.png', 'confederation' => 'CONCACAF'],
    ['name' => 'Curaçao', 'short_name' => 'CUW', 'flag' => 'https://flagcdn.com/w320/cw.png', 'confederation' => 'CONCACAF'],
    ['name' => 'Trinité-et-Tobago', 'short_name' => 'TRI', 'flag' => 'https://flagcdn.com/w320/tt.png', 'confederation' => 'CONCACAF'],
    ['name' => 'Haïti', 'short_name' => 'HAI', 'flag' => 'https://flagcdn.com/w320/ht.png', 'confederation' => 'CONCACAF'],

    // Afrique
    ['name' => 'Maroc', 'short_name' => 'MAR', 'flag' => 'https://flagcdn.com/w320/ma.png', 'confederation' => 'CAF'],
    ['name' => 'Sénégal', 'short_name' => 'SEN', 'flag' => 'https://flagcdn.com/w320/sn.png', 'confederation' => 'CAF'],
    ['name' => 'Nigeria', 'short_name' => 'NGA', 'flag' => 'https://flagcdn.com/w320/ng.png', 'confederation' => 'CAF'],
    ['name' => 'Cameroun', 'short_name' => 'CMR', 'flag' => 'https://flagcdn.com/w320/cm.png', 'confederation' => 'CAF'],
    ['name' => 'Ghana', 'short_name' => 'GHA', 'flag' => 'https://flagcdn.com/w320/gh.png', 'confederation' => 'CAF'],
    ['name' => 'Côte d\'Ivoire', 'short_name' => 'CIV', 'flag' => 'https://flagcdn.com/w320/ci.png', 'confederation' => 'CAF'],
    ['name' => 'Égypte', 'short_name' => 'EGY', 'flag' => 'https://flagcdn.com/w320/eg.png', 'confederation' => 'CAF'],
    ['name' => 'Algérie', 'short_name' => 'ALG', 'flag' => 'https://flagcdn.com/w320/dz.png', 'confederation' => 'CAF'],
    ['name' => 'Tunisie', 'short_name' => 'TUN', 'flag' => 'https://flagcdn.com/w320/tn.png', 'confederation' => 'CAF'],
    ['name' => 'Afrique du Sud', 'short_name' => 'RSA', 'flag' => 'https://flagcdn.com/w320/za.png', 'confederation' => 'CAF'],
    ['name' => 'Mali', 'short_name' => 'MLI', 'flag' => 'https://flagcdn.com/w320/ml.png', 'confederation' => 'CAF'],
    ['name' => 'Burkina Faso', 'short_name' => 'BFA', 'flag' => 'https://flagcdn.com/w320/bf.png', 'confederation' => 'CAF'],
    ['name' => 'Guinée', 'short_name' => 'GUI', 'flag' => 'https://flagcdn.com/w320/gn.png', 'confederation' => 'CAF'],
    ['name' => 'RD Congo', 'short_name' => 'COD', 'flag' => 'https://flagcdn.com/w320/cd.png', 'confederation' => 'CAF'],
    ['name' => 'Congo', 'short_name' => 'CGO', 'flag' => 'https://flagcdn.com/w320/cg.png', 'confederation' => 'CAF'],
    ['name' => 'Gabon', 'short_name' => 'GAB', 'flag' => 'https://flagcdn.com/w320/ga.png', 'confederation' => 'CAF'],
    ['name' => 'Cap-Vert', 'short_name' => 'CPV', 'flag' => 'https://flagcdn.com/w320/cv.png', 'confederation' => 'CAF'],
    ['name' => 'Guinée équatoriale', 'short_name' => 'EQG', 'flag' => 'https://flagcdn.com/w320/gq.png', 'confederation' => 'CAF'],
    ['name' => 'Zambie', 'short_name' => 'ZAM', 'flag' => 'https://flagcdn.com/w320/zm.png', 'confederation' => 'CAF'],
    ['name' => 'Zimbabwe', 'short_name' => 'ZIM', 'flag' => 'https://flagcdn.com/w320/zw.png', 'confederation' => 'CAF'],
    ['name' => 'Namibie', 'short_name' => 'NAM', 'flag' => 'https://flagcdn.com/w320/na.png', 'confederation' => 'CAF'],
    ['name' => 'Angola', 'short_name' => 'ANG', 'flag' => 'https://flagcdn.com/w320/ao.png', 'confederation' => 'CAF'],
    ['name' => 'Mozambique', 'short_name' => 'MOZ', 'flag' => 'https://flagcdn.com/w320/mz.png', 'confederation' => 'CAF'],
    ['name' => 'Bénin', 'short_name' => 'BEN', 'flag' => 'https://flagcdn.com/w320/bj.png', 'confederation' => 'CAF'],
    ['name' => 'Togo', 'short_name' => 'TOG', 'flag' => 'https://flagcdn.com/w320/tg.png', 'confederation' => 'CAF'],
    ['name' => 'Niger', 'short_name' => 'NIG', 'flag' => 'https://flagcdn.com/w320/ne.png', 'confederation' => 'CAF'],
    ['name' => 'Ouganda', 'short_name' => 'UGA', 'flag' => 'https://flagcdn.com/w320/ug.png', 'confederation' => 'CAF'],
    ['name' => 'Kenya', 'short_name' => 'KEN', 'flag' => 'https://flagcdn.com/w320/ke.png', 'confederation' => 'CAF'],
    ['name' => 'Tanzanie', 'short_name' => 'TAN', 'flag' => 'https://flagcdn.com/w320/tz.png', 'confederation' => 'CAF'],
    ['name' => 'Soudan', 'short_name' => 'SDN', 'flag' => 'https://flagcdn.com/w320/sd.png', 'confederation' => 'CAF'],
    ['name' => 'Libye', 'short_name' => 'LBY', 'flag' => 'https://flagcdn.com/w320/ly.png', 'confederation' => 'CAF'],
    ['name' => 'Mauritanie', 'short_name' => 'MTN', 'flag' => 'https://flagcdn.com/w320/mr.png', 'confederation' => 'CAF'],
    ['name' => 'Madagascar', 'short_name' => 'MAD', 'flag' => 'https://flagcdn.com/w320/mg.png', 'confederation' => 'CAF'],
    ['name' => 'Comores', 'short_name' => 'COM', 'flag' => 'https://flagcdn.com/w320/km.png', 'confederation' => 'CAF'],

    // Asie
    ['name' => 'Japon', 'short_name' => 'JPN', 'flag' => 'https://flagcdn.com/w320/jp.png', 'confederation' => 'AFC'],
    ['name' => 'Corée du Sud', 'short_name' => 'KOR', 'flag' => 'https://flagcdn.com/w320/kr.png', 'confederation' => 'AFC'],
    ['name' => 'Australie', 'short_name' => 'AUS', 'flag' => 'https://flagcdn.com/w320/au.png', 'confederation' => 'AFC'],
    ['name' => 'Iran', 'short_name' => 'IRN', 'flag' => 'https://flagcdn.com/w320/ir.png', 'confederation' => 'AFC'],
    ['name' => 'Arabie saoudite', 'short_name' => 'KSA', 'flag' => 'https://flagcdn.com/w320/sa.png', 'confederation' => 'AFC'],
    ['name' => 'Qatar', 'short_name' => 'QAT', 'flag' => 'https://flagcdn.com/w320/qa.png', 'confederation' => 'AFC'],
    ['name' => 'Émirats arabes unis', 'short_name' => 'UAE', 'flag' => 'https://flagcdn.com/w320/ae.png', 'confederation' => 'AFC'],
    ['name' => 'Chine', 'short_name' => 'CHN', 'flag' => 'https://flagcdn.com/w320/cn.png', 'confederation' => 'AFC'],
    ['name' => 'Indonésie', 'short_name' => 'IDN', 'flag' => 'https://flagcdn.com/w320/id.png', 'confederation' => 'AFC'],
    ['name' => 'Vietnam', 'short_name' => 'VIE', 'flag' => 'https://flagcdn.com/w320/vn.png', 'confederation' => 'AFC'],
    ['name' => 'Irak', 'short_name' => 'IRQ', 'flag' => 'https://flagcdn.com/w320/iq.png', 'confederation' => 'AFC'],
    ['name' => 'Ouzbékistan', 'short_name' => 'UZB', 'flag' => 'https://flagcdn.com/w320/uz.png', 'confederation' => 'AFC'],
    ['name' => 'Thaïlande', 'short_name' => 'THA', 'flag' => 'https://flagcdn.com/w320/th.png', 'confederation' => 'AFC'],
    ['name' => 'Jordanie', 'short_name' => 'JOR', 'flag' => 'https://flagcdn.com/w320/jo.png', 'confederation' => 'AFC'],
    ['name' => 'Oman', 'short_name' => 'OMA', 'flag' => 'https://flagcdn.com/w320/om.png', 'confederation' => 'AFC'],
    ['name' => 'Bahreïn', 'short_name' => 'BHR', 'flag' => 'https://flagcdn.com/w320/bh.png', 'confederation' => 'AFC'],
    ['name' => 'Koweït', 'short_name' => 'KUW', 'flag' => 'https://flagcdn.com/w320/kw.png', 'confederation' => 'AFC'],
    ['name' => 'Syrie', 'short_name' => 'SYR', 'flag' => 'https://flagcdn.com/w320/sy.png', 'confederation' => 'AFC'],
    ['name' => 'Palestine', 'short_name' => 'PLE', 'flag' => 'https://flagcdn.com/w320/ps.png', 'confederation' => 'AFC'],
    ['name' => 'Liban', 'short_name' => 'LBN', 'flag' => 'https://flagcdn.com/w320/lb.png', 'confederation' => 'AFC'],
    ['name' => 'Inde', 'short_name' => 'IND', 'flag' => 'https://flagcdn.com/w320/in.png', 'confederation' => 'AFC'],
    ['name' => 'Corée du Nord', 'short_name' => 'PRK', 'flag' => 'https://flagcdn.com/w320/kp.png', 'confederation' => 'AFC'],
    ['name' => 'Malaisie', 'short_name' => 'MAS', 'flag' => 'https://flagcdn.com/w320/my.png', 'confederation' => 'AFC'],
    ['name' => 'Philippines', 'short_name' => 'PHI', 'flag' => 'https://flagcdn.com/w320/ph.png', 'confederation' => 'AFC'],
    ['name' => 'Singapour', 'short_name' => 'SIN', 'flag' => 'https://flagcdn.com/w320/sg.png', 'confederation' => 'AFC'],
    ['name' => 'Tadjikistan', 'short_name' => 'TJK', 'flag' => 'https://flagcdn.com/w320/tj.png', 'confederation' => 'AFC'],
    ['name' => 'Kirghizistan', 'short_name' => 'KGZ', 'flag' => 'https://flagcdn.com/w320/kg.png', 'confederation' => 'AFC'],
    ['name' => 'Turkménistan', 'short_name' => 'TKM', 'flag' => 'https://flagcdn.com/w320/tm.png', 'confederation' => 'AFC'],
    ['name' => 'Hong Kong', 'short_name' => 'HKG', 'flag' => 'https://flagcdn.com/w320/hk.png', 'confederation' => 'AFC'],
    ['name' => 'Yémen', 'short_name' => 'YEM', 'flag' => 'https://flagcdn.com/w320/ye.png', 'confederation' => 'AFC'],

    // Océanie
    ['name' => 'Nouvelle-Zélande', 'short_name' => 'NZL', 'flag' => 'https://flagcdn.com/w320/nz.png', 'confederation' => 'OFC'],
    ['name' => 'Nouvelle-Calédonie', 'short_name' => 'NCL', 'flag' => 'https://flagcdn.com/w320/nc.png', 'confederation' => 'OFC'],
    ['name' => 'Tahiti', 'short_name' => 'TAH', 'flag' => 'https://flagcdn.com/w320/pf.png', 'confederation' => 'OFC'],
    ['name' => 'Fidji', 'short_name' => 'FIJ', 'flag' => 'https://flagcdn.com/w320/fj.png', 'confederation' => 'OFC'],
    ['name' => 'Papouasie-Nouvelle-Guinée', 'short_name' => 'PNG', 'flag' => 'https://flagcdn.com/w320/pg.png', 'confederation' => 'OFC'],
    ['name' => 'Salomon', 'short_name' => 'SOL', 'flag' => 'https://flagcdn.com/w320/sb.png', 'confederation' => 'OFC'],
    ['name' => 'Vanuatu', 'short_name' => 'VAN', 'flag' => 'https://flagcdn.com/w320/vu.png', 'confederation' => 'OFC'],
];
